#!/usr/bin/env node
/**
 * Daily insights generator for storeauditor.au.
 *
 * Reads `content/blog-calendar.json`, finds the next pending entry, calls the
 * Anthropic Messages API to generate a 1100-1500 word article matching the
 * brand voice rules, validates it, writes the markdown, runs `npm run build`
 * to confirm schema validity, updates the calendar, and writes a commit
 * message to /tmp/commit-msg.txt.
 *
 * Emits these GitHub Actions outputs (when $GITHUB_OUTPUT is set):
 *   - slug:    article slug
 *   - day:     1..100
 *   - title:   article title
 *   - changed: "true" if there is something for the workflow to commit
 *
 * Required env:
 *   - ANTHROPIC_API_KEY
 *
 * Optional env:
 *   - ANTHROPIC_MODEL (default: claude-sonnet-4-5)
 *   - OVERRIDE_DATE   (YYYY-MM-DD, for manual backfills)
 */

import { readFile, writeFile, unlink, appendFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";

const ROOT = process.cwd();
const CALENDAR = path.join(ROOT, "content/blog-calendar.json");
const INSIGHTS_DIR = path.join(ROOT, "src/content/insights");
const COMMIT_MSG_PATH = "/tmp/commit-msg.txt";

const API_KEY = process.env.ANTHROPIC_API_KEY;
const MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-5";
const MAX_RETRIES = 5;

if (!API_KEY) {
  console.error("ERROR: ANTHROPIC_API_KEY env var is required.");
  process.exit(1);
}

function todayDateStr() {
  if (process.env.OVERRIDE_DATE) return process.env.OVERRIDE_DATE;
  // Use Australia/Sydney local date so publishedDate matches the day the post
  // actually publishes for Sydney readers. GitHub runners are UTC, and the
  // 23:00 UTC cron crosses the date line into AEST/AEDT same-day.
  // en-CA locale returns YYYY-MM-DD.
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Australia/Sydney",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());
}

function nowISO() {
  return new Date().toISOString();
}

async function emitOutput(key, value) {
  if (!process.env.GITHUB_OUTPUT) return;
  await appendFile(process.env.GITHUB_OUTPUT, `${key}=${value}\n`);
}

async function main() {
  // 1. Read calendar
  const originalCalendarText = await readFile(CALENDAR, "utf-8");
  const calendar = JSON.parse(originalCalendarText);

  // 2. Find next pending
  const entryIndex = calendar.posts.findIndex((p) => p.status === "pending");
  if (entryIndex === -1) {
    console.log("Calendar complete. No pending entries.");
    await emitOutput("changed", "false");
    return;
  }
  const entry = calendar.posts[entryIndex];
  console.log(`Day ${entry.day}/100: ${entry.slug} (${entry.category})`);

  // 3. Duplicate check
  const filePath = path.join(INSIGHTS_DIR, `${entry.slug}.md`);
  if (existsSync(filePath)) {
    console.log("Article already exists. Marking calendar entry done (no-op).");
    calendar.posts[entryIndex] = {
      ...entry,
      status: "done",
      publishedAt: nowISO(),
    };
    await writeFile(CALENDAR, JSON.stringify(calendar, null, 2) + "\n");
    await writeFile(
      COMMIT_MSG_PATH,
      `chore(insights): mark ${entry.slug} as done (file already existed)\n\nDay ${entry.day} of 100. Auto-generated by daily-blog GitHub Action.\n`
    );
    await emitOutput("slug", entry.slug);
    await emitOutput("day", String(entry.day));
    await emitOutput("title", entry.slug);
    await emitOutput("changed", "true");
    return;
  }

  // 4. Generate with retries
  let generated = null;
  let lastError = null;
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    console.log(`Generation attempt ${attempt}/${MAX_RETRIES}...`);
    try {
      const json = await callAnthropic(entry, lastError);
      validateGenerated(json, entry);
      generated = json;
      break;
    } catch (e) {
      lastError = e.message;
      console.error(`Attempt ${attempt} failed: ${e.message}`);
      if (attempt === MAX_RETRIES) {
        console.error("All attempts exhausted. Failing.");
        process.exit(1);
      }
    }
  }

  // 5. Write article
  const frontmatter = buildFrontmatter(generated, entry);
  const fullContent = frontmatter + "\n\n" + generated.markdownBody.trim() + "\n";
  await writeFile(filePath, fullContent);
  console.log(`Wrote ${filePath}`);

  // 6. Update calendar
  calendar.posts[entryIndex] = {
    ...entry,
    status: "done",
    publishedAt: nowISO(),
  };
  await writeFile(CALENDAR, JSON.stringify(calendar, null, 2) + "\n");

  // 7. Validate via Astro build
  console.log("Running `npm run build` to validate schema...");
  try {
    execSync("npm run build", { stdio: "inherit" });
  } catch (e) {
    console.error("Build failed. Reverting calendar + file.");
    await unlink(filePath).catch(() => {});
    await writeFile(CALENDAR, originalCalendarText);
    process.exit(1);
  }

  // 8. Commit message
  const remaining = calendar.posts.filter((p) => p.status === "pending").length;
  const subject = `feat(insights): ${generated.title}`;
  const body = [
    `Day ${entry.day} of 100. ${remaining} pending.`,
    "",
    "Auto-generated by daily-blog GitHub Action.",
  ].join("\n");
  await writeFile(COMMIT_MSG_PATH, `${subject}\n\n${body}\n`);

  // 9. Emit outputs
  await emitOutput("slug", entry.slug);
  await emitOutput("day", String(entry.day));
  await emitOutput("title", generated.title);
  await emitOutput("changed", "true");

  console.log(`✓ Day ${entry.day} published: ${generated.title}`);
  console.log(`  /insights/${entry.slug}`);
  console.log(`  ${remaining} posts remaining.`);
}

async function callAnthropic(entry, prevError) {
  const internalLinksLine = entry.internalLinks
    .map((s) => `/insights/${s}`)
    .join(", ");

  const systemPrompt = [
    "You are a senior technical writer for storeauditor.au, the marketing site for Store Auditor (a Shopify performance and security audit app built by Defyn Digital).",
    "",
    "Write one insight article. Output ONLY a single JSON object (no preamble, no code fences, no commentary outside the JSON) with this exact shape:",
    "",
    "{",
    '  "title": "string, max 80 chars, MUST include the primary keyword",',
    '  "description": "string, max 170 chars, MUST include the primary keyword, ends with a benefit",',
    '  "secondaryKeywords": ["3 to 5 long-tail related keywords as strings"],',
    '  "readingTime": <integer between 6 and 12>,',
    '  "markdownBody": "the full article body as a single markdown string, 1100 to 1500 words"',
    "}",
    "",
    "NON-NEGOTIABLE RULES:",
    "",
    "1. ZERO EM-DASHES (U+2014, the long dash) anywhere in title, description, secondaryKeywords, or markdownBody. Use period, comma, colon, or parentheses instead. ANY em-dash will reject the article.",
    "2. Body length: 1100 to 1600 words. Count carefully. Aim for 1300.",
    "3. Voice: short sentences. Technical but plain. No marketing fluff. No hedging weasel words like \"potentially\", \"could possibly\", \"might perhaps\".",
    "4. Body structure:",
    "   - One sentence intro that directly answers what the article is about (the AI search engines quote this). No preamble like \"In this article we will...\".",
    "   - EXACTLY 4 to 7 H2 sections (## ...). Not 8. Count them. The final \"Wrap-up\" or \"Conclusion\" H2 counts as one of those.",
    "   - 0 to 3 H3 subsections per H2 if useful.",
    "   - One short conclusion section (## Wrap-up or similar).",
    "5. REQUIRED internal links (must appear verbatim in body):",
    `   - Each of these paths: ${internalLinksLine}`,
    "   - At least one of: /how-it-works, /pricing, /find-slow-shopify-apps",
    "6. REQUIRED Defyn backlink: 1 or 2 contextual links to https://defyn.com.au.",
    "7. No fabricated statistics. Frame numbers as observed ranges (\"we typically see 200 to 500 ms\"), never as universal facts.",
    "8. Markdown code fences (```) when useful (Liquid, JS, CLI). Fence them properly.",
    "9. Use markdown link syntax [anchor text](path), not bare URLs.",
    prevError
      ? `\nPREVIOUS ATTEMPT FAILED VALIDATION: ${prevError}\nFix this specific issue in this attempt.`
      : "",
  ].join("\n");

  const userPrompt = [
    `Today is ${todayDateStr()}.`,
    "",
    "Calendar entry to write:",
    "",
    `- Day: ${entry.day} of 100`,
    `- Slug: ${entry.slug}`,
    `- Category: ${entry.category}`,
    `- Primary keyword: ${entry.primaryKeyword}`,
    `- Angle: ${entry.angle}`,
    `- Required internal links: ${internalLinksLine}`,
    "",
    "Output ONLY the JSON object. Begin with { and end with }.",
  ].join("\n");

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-api-key": API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 8000,
      temperature: 0.7,
      system: systemPrompt,
      messages: [{ role: "user", content: userPrompt }],
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Anthropic API ${res.status}: ${text.slice(0, 500)}`);
  }

  const data = await res.json();
  const text = data?.content?.[0]?.text?.trim();
  if (!text) throw new Error("No text content in API response");

  // Strip code fences if the model added them despite instructions
  const cleaned = text
    .replace(/^```(?:json)?\s*\n?/, "")
    .replace(/\n?```\s*$/, "")
    .trim();

  try {
    return JSON.parse(cleaned);
  } catch (e) {
    throw new Error(
      `JSON parse failed: ${e.message}. Text starts with: ${cleaned.slice(0, 200)}`
    );
  }
}

function validateGenerated(g, entry) {
  if (!g || typeof g !== "object") throw new Error("Response is not an object");

  if (typeof g.title !== "string" || g.title.length === 0) {
    throw new Error("Missing or empty title");
  }
  if (g.title.length > 80) {
    throw new Error(`Title too long (${g.title.length} > 80): "${g.title}"`);
  }
  if (g.title.includes("—")) throw new Error("Title contains em-dash");

  if (typeof g.description !== "string" || g.description.length === 0) {
    throw new Error("Missing or empty description");
  }
  if (g.description.length > 170) {
    throw new Error(`Description too long (${g.description.length} > 170)`);
  }
  if (g.description.includes("—")) {
    throw new Error("Description contains em-dash");
  }

  if (!Array.isArray(g.secondaryKeywords)) {
    throw new Error("secondaryKeywords must be an array");
  }
  if (g.secondaryKeywords.length < 3 || g.secondaryKeywords.length > 5) {
    throw new Error(
      `secondaryKeywords must have 3-5 items (got ${g.secondaryKeywords.length})`
    );
  }
  if (
    g.secondaryKeywords.some(
      (k) => typeof k !== "string" || k.includes("—")
    )
  ) {
    throw new Error("secondaryKeywords contain non-strings or em-dashes");
  }

  if (
    !Number.isInteger(g.readingTime) ||
    g.readingTime < 6 ||
    g.readingTime > 12
  ) {
    throw new Error(`readingTime must be integer 6-12 (got ${g.readingTime})`);
  }

  if (typeof g.markdownBody !== "string") {
    throw new Error("Missing markdownBody");
  }

  if (g.markdownBody.includes("—")) {
    const idx = g.markdownBody.indexOf("—");
    const ctx = g.markdownBody.slice(Math.max(0, idx - 50), idx + 50);
    throw new Error(`markdownBody contains em-dash near: "...${ctx}..."`);
  }

  const words = g.markdownBody.split(/\s+/).filter(Boolean).length;
  if (words < 1100) {
    throw new Error(`Body too short: ${words} words (need 1100-1600)`);
  }
  if (words > 1600) {
    throw new Error(`Body too long: ${words} words (need 1100-1600)`);
  }

  const h2Count = (g.markdownBody.match(/^##\s+/gm) || []).length;
  if (h2Count < 4) {
    throw new Error(`Too few H2 sections: ${h2Count} (need 4-7)`);
  }
  if (h2Count > 7) {
    throw new Error(`Too many H2 sections: ${h2Count} (need 4-7)`);
  }

  for (const slug of entry.internalLinks) {
    if (!g.markdownBody.includes(`/insights/${slug}`)) {
      throw new Error(`Missing required internal link to /insights/${slug}`);
    }
  }

  if (
    !/(\/how-it-works|\/pricing|\/find-slow-shopify-apps)/.test(g.markdownBody)
  ) {
    throw new Error(
      "Missing required link to one of: /how-it-works, /pricing, /find-slow-shopify-apps"
    );
  }

  if (!g.markdownBody.includes("https://defyn.com.au")) {
    throw new Error("Missing required link to https://defyn.com.au");
  }
}

function buildFrontmatter(g, entry) {
  const escape = (s) => JSON.stringify(s);
  const lines = [
    "---",
    `title: ${escape(g.title)}`,
    `description: ${escape(g.description)}`,
    `primaryKeyword: ${escape(entry.primaryKeyword)}`,
    "secondaryKeywords:",
    ...g.secondaryKeywords.map((k) => `  - ${escape(k)}`),
    `category: ${entry.category}`,
    `publishedDate: ${todayDateStr()}`,
    `readingTime: ${g.readingTime}`,
    "---",
  ];
  return lines.join("\n");
}

main().catch((e) => {
  console.error("Fatal error:", e.stack || e.message);
  process.exit(1);
});
